### PR TITLE
Updated master server listings

### PR DESCRIPTION
**Pull request by JustinBenedick**
Added new master server listings to account for official server shutdown. Included server listings from oldunreal and 333networks.

https://www.oldunreal.com/wiki/index.php?title=Masterserver_Guide https://333networks.com/instructions/ut/c

### CODE REVIEW

**Comment by dudleycodes** [comment]
What does a dedicated server, benefit from by having a 'master list' of other dedicated servesr?

**Comment by JustinBenedick** [comment]
This is mostly for restoring online functionally and public server listing since Gamespy was taken down in 2014 and the official master server was taken offline by Epic in December 2022.  With this adjustment the sever can be listed publicly in the modernized and modified clients maintained by oldunreal, 333networks, and other groups.  

As far as I know these community master servers are being maintained and will not be decommissioned. If one is taken down there will still be a dozen remaining.


There are no performance issues.

**Comment by JustinBenedick** [comment]
To address all issues this will be turnred into an Alternative INI file

**Comment by dudleycodes** [comment]
After discussing, we are going create a separate INI file, for online servers; and keep the default INI file optimized for LANs.

**Pull request closed without merging**
